### ISSUE TITLE
Terraforged and Nature's Aura incompatibility

### ISSUE THREAD

**Issue by GryphonTheBard** [TerraForged/TerraForged#157]
**Description**
Nature's Aura is a mod revolving around performing rituals and crafting things to utilize the nature's magic. The main method of doing this is the Ritual of The Forest, where you place a variety of things around a tree sapling, let the sapling grow, and then the process begins. I had tried to do this several times, but nothing happened after the tree grew. Looking into the Github issues for Nature's Aura, another guy was digging through the files and found that Terraforged was the cause of the issue. Apparently, Nature's Aura has different magic types for different dimensions, and somehow it gets confused with Terraforged because it might be considering it to be a new dimension, despite it being the overworld. I'm not really a code or fancy computer guy, so his findings on Github may be more helpful.

**How to reproduce**
I have a pretty long list of mods installed right now, but the vast majority of them are just decorative or other things that I doubt would effect this mod, but I will put them here anyway to be a good boy. The easiest way for me to do it would probably be to put a screenshot of the mods, so I'll do that. To recreate the issue, get the Nature's Aura book, and perform the Ritual of the Forest exactly how it describes (it even has a helpful template). If the same issue occurs, the tree should grow (by either time or bonemeal) and nothing will happen instead of the shiny and glow-y ritual of the forest. (I provided the mod list I had, however I had tested it with just Terraforged and Nature'S Aura and it still did not work)
![image](https://user-images.githubusercontent.com/26839988/80650663-67abac00-8a42-11ea-83d8-b513bdc1b738.png)

**Additional information**
Here is the mod page for Nature's Aura: 
https://www.curseforge.com/minecraft/mc-mods/natures-aura
And Here is the Github of the guy who figured this out:
https://github.com/Ellpeck/NaturesAura/issues/101

This is an image of the ritual after complete set-up, but it is not doing what it should. A video of it working correctly is on the mod page. This picture was taken with every mod except for Nature's Aura, Nature's Aura's dependencies, and Terraforged removed.

![image](https://user-images.githubusercontent.com/26839988/80651633-3d5aee00-8a44-11ea-939f-235691c1be46.png)

**Comment by dags-** [comment]
You might need to disable TerraForged's 'custom biome features' (ie custom trees).

When a sapling attempts to grow into a tree TerraForged steps in to prevent the original vanilla tree from growing and instead places one of its own. The act of preventing the vanilla tree from growing may make NA not realise that a tree has been placed so it doesn't do its thing.

Testing with TF's custom trees disabled should confirm this

**Comment by GryphonTheBard** [comment]
I can confirm that turning off custom biome features does allow the mod to function properly. I wonder if there is any way around this?

**Comment by dags-** [comment]
Ah, turns out it's just an 'event priority' issue.

TF and NA use the same default priority for the sapling grow event, so who gets the event first is whoever registered the listener earliest (TF).

TF changes the sapling block to log during the event so when NA's listener gets its turn there's no sapling to detect.

Sounds NA doesn't want to fix it from that issue thread so I can just set my listener's event priority lower to make sure it runs later.

**Comment by dags-** [comment]
Should be fixed in 0.0.13

**Comment by NillerMedDild** [comment]
I'm afraid this issue still exists in `TerraForged-1.15.2-0.1.2` and `NaturesAura-28.5`

**Comment by dags-** [comment]
Oh right... the event priority has gone walkabouts since the last big refactor.
Needs this on TF's sapling listener:
```java
@SubscribeEvent(priority = EventPriority.LOWEST)
```

**Comment by NillerMedDild** [comment]
Would it be possible to get a version with that fix for 1.15.2? This bug is making Nature's Aura useless/progression locked :(

**Comment by lumimanic** [comment]
Just wondering is anyone had figured anything out in regards to this issue? we are playing with both in a modpack and it is also happening with our pack. switching to using BoP or base minecraft world generation fixes it, i was just hoping we didnt have to restart again. I tried the old fix, but it is still not working for us.

**Comment by NillerMedDild** [comment]
Yes, the fix has been found:

> 
> 
> Oh right... the event priority has gone walkabouts since the last big refactor.
> Needs this on TF's [sapling listener](https://github.com/TerraForged/TerraForged/blob/master/src/main/java/com/terraforged/mod/feature/sapling/SaplingListener.java#L64):
> 
> ```java
> @SubscribeEvent(priority = EventPriority.LOWEST)
> ```

It just hasn't been implemented :)

**Comment by lumimanic** [comment]
That is awesome! Thank you, we appreciate it for sure! Sorry If I misunderstood the previous conversation about it, it seems like I may have. \o/ Loving this mod so this is great news!

**Comment by NillerMedDild** [comment]
Thanks for the fix :)
